Unlock with fingerprint on notification double tap without pin/passwa…
crdroidandroid/android_packages_apps_crDroidSettings pull request #563
Opened 2020-04-09 19:05 UTC by Hikari-no-Tenshi

…rd/pattern [2/2]

2020-04-11 16:08 UTC, gwolf2u approved these changes

2020-04-11 16:08 UTC, gwolf2u commented
good to go here

2020-04-11 16:09 UTC, gwolf2u commented
@neobuddy89 need to change to something else or merge as is?

2020-04-11 16:22 UTC, neobuddy89 commented
@gwolf2u @Hikari-no-Tenshi Can we please make title string more crisp and summary string more elaborate? I am still unsure if this feature is useful for non-FOD devices... but let me test it more.

2020-04-13 17:12 UTC, gwolf2u requested changes

2020-04-13 17:12 UTC, gwolf2u commented on res/values/cr_strings.xml
> +    <string name="unlock_without_bouncer_title">Fingerprint unlock on notification double tap</string>
propose string change (or something similar)
"Use fingerprint unlock to view notification"

2020-04-13 17:12 UTC, gwolf2u commented on res/values/cr_strings.xml
> +    <string name="unlock_without_bouncer_summary">Unlock device with fingerprint on notification double tap without pin/password/pattern</string>
and here add "without need to input"
"Unlocks device with fingerprint on notification double tap without need to input pin/password/pattern"

2020-04-13 19:43 UTC, gwolf2u approved these changes

2020-04-13 19:44 UTC, merged

2020-04-13 21:49 UTC, neobuddy89 commented on res/xml/crdroid_settings_lockscreen.xml
> +        <com.crdroid.settings.preferences.SecureSettingSwitchPreference
SecureSettingSwitchPreference

2020-04-13 21:49 UTC, neobuddy89 commented on src/com/crdroid/settings/fragments/LockScreen.java
> +        Settings.System.putIntForUser(resolver,
Settings.System.putIntForUser