crdroid: Ambient Edge Pulse layout [2/2]
crdroidandroid/android_packages_apps_crDroidSettings pull request #595
Opened 2020-06-02 20:08 UTC by gwolf2u

2020-06-02 20:26 UTC, neobuddy89 requested changes

2020-06-02 20:26 UTC, neobuddy89 commented on res/values/cr_strings.xml
> +    <string name="pulse_ambient_light_layout_title">Edge Light View</string>
Edge light view

2020-06-02 20:31 UTC, gwolf2u commented on res/values/cr_strings.xml
> +    <string name="pulse_ambient_light_layout_title">Edge Light View</string>
Tomorrow...
Turned off PC 😂

2020-06-03 07:21 UTC, gwolf2u commented on res/values/cr_strings.xml
> +    <string name="pulse_ambient_light_layout_title">Edge Light View</string>
corrected

2020-06-03 08:05 UTC, neobuddy89 approved these changes

2020-06-03 08:05 UTC, merged