crdroid: allow disable of screenshot shutter sound [2/2]
crdroidandroid/android_packages_apps_crDroidSettings pull request #941
Opened 2022-07-07 13:36 UTC by Jabiyeff

Signed-off-by: Anar Jabiyev <cebiyevanar@gmail.com>

2022-07-07 15:20 UTC, gwolf2u requested changes

2022-07-07 15:20 UTC, gwolf2u commented on res/xml/crdroid_settings_sound.xml
> +        android:icon="@drawable/ic_screenshot"
suggest to use
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/blob/12.1/res/drawable/ic_cellphone_sound.xml
as was in cr7
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/blob/11.0/res/xml/crdroid_settings_sound.xml#L51

2022-07-07 15:32 UTC, Jabiyeff commented on res/xml/crdroid_settings_sound.xml
> +        android:icon="@drawable/ic_screenshot"
Will check this how looks, thanks

2022-07-07 18:29 UTC, Jabiyeff commented on res/xml/crdroid_settings_sound.xml
> +        android:icon="@drawable/ic_screenshot"
> suggest to use https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/blob/12.1/res/drawable/ic_cellphone_sound.xml as was in cr7 https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/blob/11.0/res/xml/crdroid_settings_sound.xml#L51

Done

2022-07-08 05:31 UTC, gwolf2u approved these changes

2022-07-10 18:52 UTC, closed without merging